#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Nathan Maupin
AERO 424-500
Project 1 - Part 2
Due: 11/12/23
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp


# Planetary Constants - Earth
G = 6.67430e-11  # gravitational constant (m^3 kg^-1 s^-2)
M_earth = 5.972e24  # Earth mass (kg)
R_earth = 6371e3  # Earth radius (m)
r_orbit =  7000e3  # orbital radius (from the center of the Earth)
omega0 = np.sqrt(G * M_earth / r_orbit**3) 
R_e = 6371e3  # Earth's radius in meters


# Satellite Parameters - Moments of Inertia
I11 = 4500  # kg-m^2
I22 = 6000  # kg-m^2
I33 = 7000  # kg-m^2

# Initial Orientation Parameters
psi, phi, theta = np.array([0.09, -0.07, 0.15])
omega_B_initial = np.array([-0.0008, 0.0006, 0.00085])
initial_conditions = np.array([phi, psi, theta, *omega_B_initial])

#Inital Environment Parameters
omega_e = 7.29212e-5 #rad/s - Earth's angular velocity
m_hat = [-0.0558462, 0.169857, -0.983885]  # Normalized magnetic moment vector
m_hat = [-0.983885,-0.0558462, 0.169857]
B_0 = 3.12e-5  # Earth's magnetic field strength at the equator in Tesla

#Orbit Parameters
a = 7000e3 #m - semi-major axis
i = np.deg2rad(83) # inclination = 83 deg
w_0 = 7546.05/a 
RAAN = np.deg2rad(-70) # RAAN
u = 0 # Argument of latitude

#Solar Parameters
P = 4.644e-6  # Solar radiation pressure in N/m^2
plate_areas = np.array([5, 7, 7])
plate_normals = np.array([[0, 0, 1], [0, np.sin(np.deg2rad(30)), np.cos(np.deg2rad(30))], [0, np.sin(np.deg2rad(30)), np.cos(np.deg2rad(30))]])
plate_center_of_mass = np.array([[0.1, 0.1, 0], [2, 0, 0], [-2, 0, 0]])
plate_spec = np.array([0.8, 0.2, 0.2])
plate_diffus = np.array([0.1, 0.1, 0.1])


#Gravity Gradient Torque
def gravity_gradient(phi, psi, theta):
    MG1 = 3 * omega0**2 * ((np.cos(psi) * np.sin(phi)) * (-np.sin(theta) * np.cos(phi) + np.cos(theta) * np.sin(psi) * np.sin(phi)) * (I33 - I22))
    MG2 = 3 * omega0**2 * ((np.cos(psi) * np.sin(phi)) * (np.cos(theta) * np.cos(phi) + np.sin(theta) * np.sin(psi) * np.sin(phi)) * (I11 - I33))
    MG3 = 3 * omega0**2 * ((np.cos(theta) * np.cos(phi) + np.sin(theta) * np.sin(psi) * np.sin(phi)) * (-np.sin(theta) * np.cos(phi) + np.cos(theta) * np.sin(psi) * np.sin(phi)) * (I22 - I11))        
    return np.array([MG1, MG2, MG3])


#Electromagnetic Torque - referenced hw 3 code
def electromagnetic(t, phi, psi, theta):
    r_ecef = np.array([1, 0, 0]) * a
    r_mag = np.linalg.norm(r_ecef)
    r_hat = r_ecef / r_mag
    
    # Rotation matrix from ECI to ECEF frame
    ECI2ECEF = np.array([[np.cos(-omega_e * t), -np.sin(-omega_e * t), 0],
                         [np.sin(-omega_e * t), np.cos(-omega_e * t), 0],
                         [0, 0, 1]
                         ])
    
    ECEF2ECI = np.transpose(ECI2ECEF)
    
    #3-1-3 Rotation Matrix
    ECI2Orbit = np.array([
        [np.cos(u)*np.cos(RAAN)-np.sin(u)*np.cos(i)*np.sin(RAAN), np.cos(u)*np.sin(RAAN)+np.sin(u)*np.cos(i)*np.cos(RAAN), np.sin(u)*np.sin(i)],
        [-np.sin(u)*np.cos(RAAN)-np.cos(u)*np.cos(i)*np.sin(RAAN), -np.sin(u)*np.sin(RAAN)+np.cos(u)*np.cos(i)*np.cos(RAAN), np.cos(u)*np.sin(i)],
        [np.sin(i)*np.sin(RAAN), -np.sin(i)*np.cos(RAAN), np.cos(i)]
        ])
    
    #2-1-3 Rotation Matrix
    Orbit2Body = np.array([
        [np.cos(theta)*np.cos(phi)+np.sin(theta)*np.sin(psi)*np.sin(phi), np.sin(theta)*np.cos(psi), -np.cos(theta)*np.sin(phi)+np.sin(theta)*np.sin(psi)*np.cos(phi)],
        [-np.sin(theta)*np.cos(phi)+np.cos(theta)*np.sin(psi)*np.sin(phi), np.cos(theta)*np.cos(psi), np.sin(theta)*np.sin(phi)+np.cos(theta)*np.sin(psi)*np.cos(phi)],
        [np.cos(psi)*np.sin(phi), -np.sin(psi), np.cos(psi)*np.cos(phi)]
        ])
                
    # Transform Magnetic Field to Satellite Body Frame
    m_eci = np.dot(ECEF2ECI, m_hat)
    m_orbit = np.dot(ECI2Orbit, m_eci)
    m_body = np.dot(Orbit2Body, m_orbit)
    
    B_body = B_0 * (R_e / r_mag)**3 * (3 * (np.dot(m_body, r_hat)) * r_hat - m_body)
    
    # Store magnetic field magnitudes in body frame
    M = 3 * np.array([1, 1, 1])  # 3 ampere-m^2 aligned with pitch axis
  
    # Calculate Torque
    torque = np.cross(M, B_body)
    
    return torque


def calculate_s_hat(t, phi, psi, theta):
    omega_r = 2*np.pi/(365*24*60*60)
    tilt = np.deg2rad(23.5)
    
    R3_w_0 = np.array([
        [np.cos(w_0*t), np.sin(w_0*t), 0],
        [-np.sin(w_0*t), np.cos(w_0*t), 0],
        [0, 0, 1]
        ])

    R1_i = np.array([
        [1, 0, 0],
        [0, np.cos(i), np.sin(i)],
        [0, -np.sin(i), np.cos(i)]
        ])

    R3_RAAN = np.array([
        [np.cos(RAAN), np.sin(RAAN), 0],
        [-np.sin(RAAN), np.cos(RAAN), 0],
        [0, 0, 1]
        ])

    R1_tilt = np.array([
        [1, 0, 0],
        [0, np.cos(tilt), np.sin(tilt)],
        [0, -np.sin(tilt), np.cos(tilt)]
        ])   
    
    Orbit2Body = np.array([
        [np.cos(theta)*np.cos(phi)+np.sin(theta)*np.sin(psi)*np.sin(phi), np.sin(theta)*np.cos(psi), -np.cos(theta)*np.sin(phi)+np.sin(theta)*np.sin(psi)*np.cos(phi)],
        [-np.sin(theta)*np.cos(phi)+np.cos(theta)*np.sin(psi)*np.sin(phi), np.cos(theta)*np.cos(psi), np.sin(theta)*np.sin(phi)+np.cos(theta)*np.sin(psi)*np.cos(phi)],
        [np.cos(psi)*np.sin(phi), -np.sin(psi), np.cos(psi)*np.cos(phi)]
        ])
    
    s_hat_ecliptic = np.array([np.cos(omega_r*t), np.sin(omega_r*t), 0])
    
    meh1  = np.dot(s_hat_ecliptic, R1_tilt)
    meh2 = np.dot(meh1, R3_RAAN)
    meh3 = np.dot(meh2, R1_i)
    meh4 = np.dot(meh3, R3_w_0)
    s_hat_body = np.dot(meh4, Orbit2Body)
    
    return s_hat_body


#Solar Pressure Torque  
def solar_torque(t, phi, psi, theta):
    s_hat = calculate_s_hat(t, phi, psi, theta)
    total_torque = np.zeros(3)
    for i in range(3):
        n_hat = plate_normals[i]
        A = plate_areas[i]
        r = plate_center_of_mass[i]
        force = P * A * (np.dot(n_hat, s_hat)) * ((1 - plate_spec[i]) * s_hat + (plate_spec[i] + 2/3 * plate_diffus[i]) * n_hat)
        torque = np.cross(r, force)
        total_torque += torque
    return total_torque

    
# Dynamics function for ODE solver
def satellte_angular_rates(t, y):
    
    phi, psi, theta, omega1, omega2, omega3 = y
    
    MG = gravity_gradient(phi, psi, theta)
    SR = solar_torque(t, phi, psi, theta)
    EM = electromagnetic(t, phi, psi, theta)
    
    # Euler's equations of motion
    tau1 = MG[0] + EM[0] + SR[0]
    tau2 = MG[1] + EM[1] + SR[1]
    tau3 = MG[2] + EM[2] + SR[2]
    
    """
    tau1 = MG[0]
    tau2 = MG[1]
    tau3 = MG[2]

    
    # Euler's equations of motion
    tau1 = 0  # Assuming no external torques for simplicity
    tau2 = 0
    tau3 = 0
    """
    
    dot_omega1 = (tau1 - (I33 - I22) * omega2 * omega3) / I11
    dot_omega2 = (tau2 - (I11 - I33) * omega1 * omega3) / I22
    dot_omega3 = (tau3 - (I22 - I11) * omega1 * omega2) / I33
    
    # Angle rate equations
    dot_phi = (omega1 * np.sin(theta) + omega2 * np.cos(theta) - omega0 * np.sin(psi) * np.cos(phi)) / np.cos(psi)
    dot_psi = (omega1 * np.cos(theta) - omega2 * np.sin(theta)) + omega0 * np.sin(phi)
    dot_theta = (omega1 * np.sin(theta) + omega2 * np.cos(theta)) * np.tan(psi) - omega0 * np.cos(phi) / np.cos(psi) + omega3
    
    return [dot_phi, dot_psi, dot_theta, dot_omega1, dot_omega2, dot_omega3]


# Integrate dynamics over 3 orbits
T_orbit = 2 * np.pi / omega0  # Orbital period
T_orbit = (2 * np.pi*r_orbit) / np.sqrt((G*M_earth)/r_orbit)
time_span = (0, 3 * T_orbit)
solution = solve_ivp(satellte_angular_rates, time_span, initial_conditions, t_eval=np.linspace(*time_span, 1000))

""" Plot angles """
plt.figure(figsize=(12, 8))

plt.subplot(3, 1, 1)
plt.plot(solution.t / T_orbit, np.degrees(solution.y[0]), label='Roll ($\phi$)')
plt.ylabel('Angle (degrees)')
plt.legend()
plt.title("Satellite Orientation")

plt.subplot(3, 1, 2)
plt.plot(solution.t / T_orbit, np.degrees(solution.y[1]), label='Yaw ($\psi$)')
plt.ylabel('Angle (degrees)')
plt.legend()

plt.subplot(3, 1, 3)
plt.plot(solution.t / T_orbit, np.degrees(solution.y[2]), label='Pitch ($\theta$)')
plt.xlabel('Orbit Number')
plt.ylabel('Angle (degrees)')
plt.legend()

plt.tight_layout()
plt.show()
